// Script para ayudar a debuggear el localStorage del frontend
console.log('🔍 Instrucciones para debuggear el localStorage:');
console.log('');
console.log('1. Abre el navegador y ve a http://localhost:4200');
console.log('2. Abre las herramientas de desarrollador (F12)');
console.log('3. Ve a la pestaña "Console"');
console.log('4. Ejecuta estos comandos uno por uno:');
console.log('');
console.log('// Verificar si hay token guardado');
console.log('localStorage.getItem("token")');
console.log('');
console.log('// Verificar si hay usuario guardado');
console.log('localStorage.getItem("user")');
console.log('');
console.log('// Limpiar localStorage (si es necesario)');
console.log('localStorage.clear()');
console.log('');
console.log('// Verificar todas las claves en localStorage');
console.log('Object.keys(localStorage)');
console.log('');
console.log('5. Después de hacer login, ejecuta de nuevo:');
console.log('localStorage.getItem("token")');
console.log('localStorage.getItem("user")');
console.log('');
console.log('6. Si el token existe, intenta ir a:');
console.log('http://localhost:4200/perfil-debug');
console.log('');
console.log('7. Revisa la consola para ver los logs del AuthGuard y AuthService');
console.log('');
console.log('💡 Si el token no se está guardando, el problema está en el login.');
console.log('💡 Si el token existe pero el AuthGuard bloquea, el problema está en la validación.');
console.log('💡 Si todo funciona en /perfil-debug, el problema está en el AuthGuard.');